branches:
  only:
    - master

language: node_js

sudo: false

node_js: stable

cache:
  directories:
    - node_modules

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install

before_script:
  - git config --global user.name "SmallStoneSK"
  - git config --global user.email "575913857@qq.com"
  - npm run clean

script:
  - npm run build

after_success:
  - git add --all .
  - git commit --message "Deploy from travis-ci"
  - git push --quiet --force  "https://${GH_TOKEN}@${GH_REF}" gh-pages

# Note: you should set Environment Variables here or 'Settings' on travis-ci.org
env:
  global:
    - GH_REF: github.com/SmallStoneSK/leetcode-traning-notes.git